
#Настройки игры
SCREEN_WIDTH, SCREEN_HEIGHT = 800, 500
FPS = 30
SCROLL_SPEED = 8
GRAVITY = 1.5

#Настройки птички
BIRD_WIDTH, BIRD_HEIGHT = 50, 50
BIRD_POSITION = (SCREEN_WIDTH // 4, SCREEN_HEIGHT // 2)
ANIMATION_TIME = 150
JUMP = -15

#Настройки труб
PIPE_WIDTH, PIPE_HEIGHT = 100, SCREEN_HEIGHT
PIPE_DISTANCE = 300
PIPE_GAP = 150
TOP_PIPE_START = PIPE_GAP // 2
BOT_PIPE_START = PIPE_GAP + PIPE_GAP // 2 + 325

